CHORDS = {
    "A": {
        "short_name": "A",
        "full_name": "A major",
        "type": "major",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["0", "2", "2", "2", "0", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Am": {
        "short_name": "Am",
        "full_name": "A minor",
        "type": "minor",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["0", "1", "2", "2", "0", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "B": {
        "short_name": "B",
        "full_name": "B major",
        "type": "major",
        "difficulty": "medium",
        "position": "barre",
        "tab_fingering": ["2", "4", "4", "4", "2", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Bm": {
        "short_name": "Bm",
        "full_name": "B minor",
        "type": "minor",
        "difficulty": "medium",
        "position": "barre",
        "tab_fingering": ["2", "3", "4", "4", "2", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "C": {
        "short_name": "C",
        "full_name": "C major",
        "type": "major",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["0", "1", "0", "2", "3", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Cadd9": {
        "short_name": "Cadd9",
        "full_name": "C added 9th",
        "type": "add9",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["0", "3", "0", "2", "3", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "D": {
        "short_name": "D",
        "full_name": "D major",
        "type": "major",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["2", "3", "2", "0", "x", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Dm": {
        "short_name": "Dm",
        "full_name": "D minor",
        "type": "minor",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["1", "3", "2", "0", "x", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Dmaj7": {
        "short_name": "Dmaj7",
        "full_name": "D major 7th",
        "type": "major7",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["2", "2", "2", "0", "x", "x"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Dsus4": {
        "short_name": "Dsus4",
        "full_name": "D suspended 4th",
        "type": "suspended",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["3", "3", "2", "0", "x", "x"],  # e B G D A E
        "tags": [None],
        "genre_suggested": [None],
    },
    "E": {
        "short_name": "E",
        "full_name": "E major",
        "type": "major",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["0", "0", "1", "2", "2", "0"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Em": {
        "short_name": "Em",
        "full_name": "E minor",
        "type": "minor",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["0", "0", "0", "2", "2", "0"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "F": {
        "short_name": "F",
        "full_name": "F major",
        "type": "major",
        "difficulty": "hard",
        "position": "barre",
        "tab_fingering": ["1", "1", "2", "3", "3", "1"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Fm": {
        "short_name": "Fm",
        "full_name": "F minor",
        "type": "minor",
        "difficulty": "hard",
        "position": "barre",
        "tab_fingering": ["1", "1", "1", "3", "3", "1"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "G": {
        "short_name": "G",
        "full_name": "G major",
        "type": "major",
        "difficulty": "easy",
        "position": "open",
        "tab_fingering": ["3", "0", "0", "0", "2", "3"],
        "tags": [None],
        "genre_suggested": [None],
    },
    "Gm": {
        "short_name": "Gm",
        "full_name": "G minor",
        "type": "minor",
        "difficulty": "hard",
        "position": "barre",
        "tab_fingering": ["3", "3", "3", "5", "5", "3"],
        "tags": [None],
        "genre_suggested": [None],
    },
}
